language: python
python:
  - "2.7"
env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python manage.py test
